/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonType,
} from './components/button/button';

export namespace Components {
  interface NvButton {
    /**
    * If true, the button will be disabled
    */
    'disabled': boolean;
    /**
    * If true, the button will be in a loading state
    */
    'loading': boolean;
    /**
    * The type of the button
    */
    'type': ButtonType;
  }
  interface NvLayout {}
}

declare global {


  interface HTMLNvButtonElement extends Components.NvButton, HTMLStencilElement {}
  var HTMLNvButtonElement: {
    prototype: HTMLNvButtonElement;
    new (): HTMLNvButtonElement;
  };

  interface HTMLNvLayoutElement extends Components.NvLayout, HTMLStencilElement {}
  var HTMLNvLayoutElement: {
    prototype: HTMLNvLayoutElement;
    new (): HTMLNvLayoutElement;
  };
  interface HTMLElementTagNameMap {
    'nv-button': HTMLNvButtonElement;
    'nv-layout': HTMLNvLayoutElement;
  }
}

declare namespace LocalJSX {
  interface NvButton {
    /**
    * If true, the button will be disabled
    */
    'disabled'?: boolean;
    /**
    * If true, the button will be in a loading state
    */
    'loading'?: boolean;
    /**
    * The type of the button
    */
    'type'?: ButtonType;
  }
  interface NvLayout {}

  interface IntrinsicElements {
    'nv-button': NvButton;
    'nv-layout': NvLayout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'nv-button': LocalJSX.NvButton & JSXBase.HTMLAttributes<HTMLNvButtonElement>;
      'nv-layout': LocalJSX.NvLayout & JSXBase.HTMLAttributes<HTMLNvLayoutElement>;
    }
  }
}


