/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonType,
} from './components/button/button';

export namespace Components {
  interface NvButton {
    /**
    * The type of the button
    */
    'type': ButtonType;
  }
}

declare global {


  interface HTMLNvButtonElement extends Components.NvButton, HTMLStencilElement {}
  var HTMLNvButtonElement: {
    prototype: HTMLNvButtonElement;
    new (): HTMLNvButtonElement;
  };
  interface HTMLElementTagNameMap {
    'nv-button': HTMLNvButtonElement;
  }
}

declare namespace LocalJSX {
  interface NvButton {
    /**
    * The type of the button
    */
    'type'?: ButtonType;
  }

  interface IntrinsicElements {
    'nv-button': NvButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'nv-button': LocalJSX.NvButton & JSXBase.HTMLAttributes<HTMLNvButtonElement>;
    }
  }
}


